spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seodangdog-mysql.cza82kskeqwa.ap-northeast-2.rds.amazonaws.com:3306/seodangdog?
    username: seodangdog
    password: dogseodang0311
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
  data:
    mongodb:
      #      uri: mongodb://j10e104.p.ssafy.io:27017/seodangdog
      #      authentication-database: admin
      #      username: dogsoedang
      #      password: sssdangorg56
      host: j10e104.p.ssafy.io
      port: 27017
      database: seodangdog
      authentication-database: admin  # 사용자 인증에 사용되는 데이터베이스
      username: dogsoedang
      password: sssdangorg56
    redis:
      host: j10e104.p.ssafy.io
      port: 6379
      password: seodangdog
  mvc:
    servlet:
      load-on-startup: 1
server:
  port : 8081
  forward-headers-strategy: FRAMEWORK

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

jwt:
  secret: 3877e4994655b008c3cc4f3a95b5a09efe068dd09a8da9cea760dcfaaa621a3e69f1adc7e1be4b0b4fa008fe2818da4b581c52095c5418475cdca6dcf440690b
  accessTokenExpireTime : 86400000
#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.type: trace

