spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://seodangdog-mysql.cza82kskeqwa.ap-northeast-2.rds.amazonaws.com:3306/seodangdog?
    username: seodangdog
    password: dogseodang0311
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use_sql_comments: true
  data:
    mongodb:
      uri: mongodb://j10e104.p.ssafy.io:27017/seodangdog
      authentication-database: admin
      username: seodangdogi
      password: seo@7220311p!!
    redis:
      host: j10e104.p.ssafy.io
      port: 6379
      password: seodangdog
  mvc:
    servlet:
      load-on-startup: 1
server:
  port : 8081


#logging:
#  level:
#    org.hibernate.sql: debug
#    org.hibernate.type: trace